---

- name: Installation
  hosts: "{{ target | default('all') }}"
  vars_files:
    - vars/main.yml

  collections:
    - devsec.hardening

  roles:
    - { role: user, tags: ['user', 'base', 'minimal'] }
    - { role: swap, tags: ['swap', 'base', 'minimal'] }
    - { role: crontab, tags: ['crontab', 'base', 'minimal'] }
    - { role: apt, tags: ['apt', 'base', 'minimal'] }
    - { role: firewall, tags: ['firewall', 'security', 'base'] }
    - { role: fail2ban, tags: ['fail2ban', 'security', 'base'] }
    - { role: devsec.hardening.ssh_hardening, tags: ['ssh-hardening', 'hardening', 'security', 'base'] }
    - { role: devsec.hardening.os_hardening, tags: ['os-hardening', 'hardening', 'security', 'base'] }

  post_tasks:
    - shell: usermod -p "*" {{ user }} # Unlock account after ssh-hardening
...
