---

- name: Installation
  hosts: "{{ target | default('all') }}"
  vars_files:
    - vars/main.yml

  roles:
    - { role: user, tags: ['user', 'base', 'minimal'] }
    - { role: swap, tags: ['swap', 'base', 'minimal'] }
    - { role: crontab, tags: ['crontab', 'base', 'minimal'] }
    - { role: nfs, tags: ['nfs', 'base', 'minimal'], when: master is defined }
    - { role: apt, tags: ['apt', 'base', 'minimal'] }
    - { role: firewall, tags: ['firewall', 'security', 'base'] }
    - { role: fail2ban, tags: ['fail2ban', 'security', 'base'] }
    - { role: ssh-hardening, tags: ['ssh-hardening', 'hardening', 'security', 'base'] }
    - { role: os-hardening, tags: ['os-hardening', 'hardening', 'security', 'base'] }

  post_tasks:
    - shell: usermod -p "*" {{ user }} # Unlock account after ssh-hardening
...
