---

- name: Check if swap file exists
  stat:
    path: /swap
  register: swap_file_check

- name: Create swap file
  command: fallocate -l 3G /swap
  when: not swap_file_check.stat.exists

- name: Init swap file
  command: mkswap /swap
  when: not swap_file_check.stat.exists

- name: Manage swap file in /etc/fstab
  mount:
    src: /swap
    name: none
    fstype: swap
    opts: sw
    dump: 0
    passno: 0
    state: present

- name: Enable swap file
  command: swapon -a
  when: not swap_file_check.stat.exists

- name: Configure swapiness
  sysctl:
    name: vm.swappiness
    value: 10
    state: present

- name: Check if cgroup memory and swapaccount in kernel
  command: sed -i -e 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"/g' /etc/default/grub

- name: Update grub
  command: update-grub
